### ISSUE TITLE
OSM processing and data delivery workflow roadmap ideas

### ISSUE THREAD

**Issue by Robinlovelace** [udsleeds/openinfra#49]
The README outlines the objective of creating open transport infrastructure data packs. That requires a reproducible data processing workflow supported by open source code. So far most of the work has been focussed on OSM data analysis rather than this more 'data engineering' stage but we need to move in that direction. After a great conversation with @bdon today, I have clarity on key steps which form a preliminary road map, comments welcome:

- [ ] Reproducible workflow starting with regional PBF files -> R/Python
- [ ] Workflow starting with national .pbf files e.g. from Geofabrik -> osmium or another CLI tool to extract regional areas -> R/Python
- [ ] Automation of the above e.g. with local cron job or GH actions (is there enough compute there?)
- [ ] If time allows and if users need try alternative workflow using [OSMExpress](https://github.com/protomaps/OSMExpress) running locally
- [ ] Hosted solution with real time download (blue skies)

**Comment by bdon** [comment]
* Tool I recommend is [osmium-tool](https://github.com/osmcode/osmium-tool) for generating extract based on GeoJson or .POLY boundary from a source file
* Open question if GitHub Actions is a workable solution - that could be very cool, but you may hit limits on the size of repository artifacts - might be better to commit them at the end of the run to S3 or another service
* OSM Express major benefit would be working on minute-updated data which is not critical for this use case - for individual on-demand extracts it can be faster, but with osmium-tool you can generate multiple extracts in a single run - see "Creating multiple extracts in one go" https://osmcode.org/osmium-tool/manual.html#creating-geographic-extracts
